### ISSUE TITLE
EditButton on EditTrip not working

### ISSUE THREAD

**Issue by lkellar** [katzrkool/trips#88]
I'm almost 100% positive this is an iOS 14 beta bug, and probably a more recent one. Hopefully it gets fixed in beta 7.

I've tried putting the EditButton under the list of categories, which kinda works, but not really. It does look better overall though, so I think that should be kept.

![CleanShot 2020-09-02 at 12 34 23](https://user-images.githubusercontent.com/28833934/92016932-a4e9b880-ed18-11ea-9d80-c3d80bfc5c23.png)

**Comment by katzrkool** [comment]
Well, it seems to be working now, but only in the nav bar. Putting it inline breaks everything
